### ISSUE TITLE
No instructions on how to use

### ISSUE THREAD

**Issue by lismore** [danielpinto8zz6/c-cpp-project-generator#1]
Hi,

I have installed your extension and have been looking around for information on how to actually trigger it to create the project.  Can I suggest you update the project readme with an example or update your repo wiki. 

thanks

**Comment by danielpinto8zz6** [comment]
Hi mate,
I'm little busy right now but I'll do it, maybe this weekend.
Thank you

**Comment by lismore** [comment]
Thanks ,  no rush

Just some feedback that might help new users like myself get the most from it.  If I knew how to make use of the plugin I would write it myself.

**Comment by wahur666** [comment]
Since the author is too busy to write down how to use it, based on the source code, you open the F1 menu, then start typing Create C/C++ project, and it will show the options

**Comment by danielpinto8zz6** [comment]
Done https://github.com/danielpinto8zz6/c-cpp-project-generator/commit/9b69498f3c440dba18b439a7cd91e24d7e2ca700
