### ISSUE TITLE
makefile not valid in C++ project

### ISSUE THREAD

**Issue by robgal519** [danielpinto8zz6/c-cpp-project-generator#101]
**Describe the bug**
C++ project makefile is wrong! compilation flags not included in compilation command

**To Reproduce**
1. Ctrl + shift + p -> Create C++ Project
2. pick empty directory for a project ( SIDE note: it would be nice, if I could create a dir here and not rely on existing one)
3. edit src/main.cpp:
`
#include <cstddef>
int main(int argc, char *argv[])
{
std::byte b{0x30};
return 0;
}
`
( This file uses c++17 feature std::bytes, and this require -std=C++17 flag in compilation)
4. Run `make` or Ctrl + Shift + b to compile
5. Compilation Failed, and executed commands looks like:
`g++    -c -o src/main.o src/main.cpp`

**Expected behavior**
compilation command should look like that:
`g++ -std=c++17 -Wall -Wextra -g   -c -o src/main.o src/main.cpp`

**Environment**
 - VSCode Version: 1.44.0
 - OS Version: WSL1

FIX:
To fix this issue CFLAGS variable in makefile need to be renamed to CXXFLAGS in C++ projects

**Comment by danielpinto8zz6** [comment]
Hi,
I merged your pr.

btw, "SIDE note: it would be nice, if I could create a dir here and not rely on existing one"
You can already create a dir

**Comment by robgal519** [comment]
Thank you for fast response
