### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by robgal519** [danielpinto8zz6/c-cpp-project-generator#106]
**Is your feature request related to a problem? Please describe.**
Every project should have license just to be on the safe side. If there is no license, it is not clear how to treat any patches from the contributors, and it is not clear who can use the project for what purposes.

**Comment by danielpinto8zz6** [comment]
I thought I added it before
Thanks for the reminder, added: 23b0e6ac6b1a47496804404969b39f96da3e35f4
