### ISSUE TITLE
Makefile keep giving fatal no such file or directory when including custom header file

### ISSUE THREAD

**Issue by svenikea** [danielpinto8zz6/c-cpp-project-generator#138]
**Describe the bug**
I generate a custom header file named task.h inside the include folder and include the header file in my main.cpp but make seem can't find it 

**To Reproduce**
1. Ctrl + Shift + P to generate C++ project
2. Created a task.h inside the include folder
3. put #include "task.h" in main.cpp
4. type make in terminal 

**Expected behavior**
```
fatal error: task.h: no such file or directory 
```

**Environment**
 - VSCode Version: [1.44.2]
 - OS Version: [Manjaro 20.02]

**Comment by danielpinto8zz6** [comment]
put task.h in include folder
