### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by GGXBoo** [danielpinto8zz6/c-cpp-project-generator#155]
I am a novice. When using this plug-in, it is not clear what should be put in the include directory. I tried to put in some header files, but it didn't compile when I `make run`. error: No such file or directory

**Comment by GGXBoo** [comment]
Now I seem to have found the problem.What caused the problem `OBJECTS := $(SOURCES:.cpp=.o)` and `$(BIN)/$(EXECUTABLE): $(OBJECTS)`. This results in an implicit compilation of makefile ` g++  - c - o main.o main.cpp `.There was an error that could not find the header file.
terms of settlement：
```
$(BIN)/$(EXECUTABLE): $(SOURCES)
	$(CC) $(CFLAGS) $(CINCLUDES) $(CLIBS) $^ -o $@ $(LIBRARIES)  -lpthread
```
or Covert implicit conversion：
```
$(OBJECTS): $(SOURCES)
	$(CC) $(CFLAGS) $(CINCLUDES) $(CLIBS) -c $^  -o  $@ $(LIBRARIES)
```

**Comment by danielpinto8zz6** [comment]
https://github.com/danielpinto8zz6/c-cpp-project-generator/commit/687d4b7f6cfb6a599c69d2c5e04f04b7d26e9423
