### ISSUE TITLE
Put *.o file in the bin folder

### ISSUE THREAD

**Issue by momentforever** [danielpinto8zz6/c-cpp-project-generator#157]
**Is your feature request related to a problem? Please describe.**
If you could put the *.o file in the bin folder when create *.o , I think my project can be tidy. I also could write .gitignore conveniently when I use git.

**Describe the solution you'd like**
rewrite makefile,i think.(Sorry, I don't understand how to write makefile)

**Comment by danielpinto8zz6** [comment]
https://github.com/danielpinto8zz6/c-cpp-project-generator/commit/687d4b7f6cfb6a599c69d2c5e04f04b7d26e9423
