### ISSUE TITLE
clean command doesn't work on windows 10

### ISSUE THREAD

**Issue by viafx24** [danielpinto8zz6/c-cpp-project-generator#158]
**Describe the bug**
I'm using mingw-w64 ; VS code 1.49.1; windows 10 family; coding in C ; i dit not modify the makefile.

**Under powershell**, in the correct directory,  when i run "**mingw32-make clean**", i got this answer:
rm -f src/functions.o src/main.o
process_begin: CreateProcess(NULL, rm -f src/functions.o src/main.o, ...) failed.
make (e=2): Le fichier spÚcifiÚ est introuvable.
mingw32-make: [Makefile:34: clean] Error 2 (ignored)

(the third line is in french due to my OS).

depreciated: I suspect that the "rm" function doesn't work on powershell (only exist on linux)

new edit: when i use "del" in place of "rm", the files are correctly deleted. It looks like mingw32-make uses "cmd" in place of "powershell".

![image](https://user-images.githubusercontent.com/42340158/94488199-77dad980-01e2-11eb-91fe-d981852ed10d.png)

**Comment by danielpinto8zz6** [comment]
https://github.com/danielpinto8zz6/c-cpp-project-generator/commit/687d4b7f6cfb6a599c69d2c5e04f04b7d26e9423
