### ISSUE TITLE
Launch configuration pointing at bin, but this folder has been replaced by output folder

### ISSUE THREAD

**Issue by kzawad1** [danielpinto8zz6/c-cpp-project-generator#160]
**Describe the bug**
With the recent release of this extension, the previous "bin" directory that stored the executable was renamed to "output", but the launch configuration (c-cpp-project-generator/templates/launch.json) was not changed, so cannot run a launch configuration.

Get error when running and debugging.  Need to manually change the launch.json file to put the correct path of the executable.

**To Reproduce**
1. Open Visual Studio
2. Create a new "C project" using this extension.
3. Build the project.
4. Run the project in debug, an error will state that it cannot find the executable.

**Expected behavior**
Expect to go to debug without error.

**Screenshots**
None

**Environment**
 - VSCode Version: 1.50.0
 - OS Version: Ubuntu 20.04.1 LTS

**Additional context**
Extension is version 1.2.2.

**Comment by danielpinto8zz6** [comment]
Hi, fixed 👍 

https://github.com/danielpinto8zz6/c-cpp-project-generator/commit/61c6ff20f2021fe636e8e29f0782fd05144669c2
