### ISSUE TITLE
Error when trying to Build C file

### ISSUE THREAD

**Issue by alexthegreat1** [danielpinto8zz6/c-cpp-project-generator#2]
When I try to Build the template .c file created by this extension (while a built file doesn't already exist in the bin folder), it gives me errors:
`clang: error: unable to execute command: Segmentation fault: 11`
`clang: error: linker command failed due to signal (use -v to see invocation)`

However, if I edit the Makefile at line 25 and change `$(BIN)/$(EXECUTABLE): $(SRC)/*` to `$(BIN)/$(EXECUTABLE): $(SRC)/*.c`, it works and I can Build, Run, and Debug the program properly.

**Comment by danielpinto8zz6** [comment]
Yeah males sense. Ill fix it ASAP.
Thx

**Comment by romanvasicek** [comment]
I'd like to suggest another change(s) to the C project Makefile as I have issue with compilation on my Mac. Can anyone here verify that it will work on other platforms too with both single and multiple files setup?

```
CC		:= gcc
CFLAGS := -Wall -Wextra

BIN		:= bin
SRC		:= src
INCLUDE	:= include
LIB		:= lib

LIBRARIES	:=
SOURCES		= $(wildcard $(SRC)/*.c)
OBJECTS		= $(SOURCES:.c=.o)

ifeq ($(OS),Windows_NT)
EXECUTABLE	:= main.exe
else
EXECUTABLE	:= main
endif

all: $(BIN)/$(EXECUTABLE)

.PHONY:	clean
clean:
	-$(RM) $(BIN)/$(EXECUTABLE)
	-$(RM) $(OBJECTS)

run: all
	./$(BIN)/$(EXECUTABLE)

$(BIN)/$(EXECUTABLE): $(OBJECTS)
	$(CC) $(CFLAGS) -I$(INCLUDE) -L$(LIB) $^ -o $@ $(LIBRARIES)
```

Changes description:
- define SOURCES and OBJECTS file list and utilize implicit make rule to generate OBJECTS
- rename C_FLAGS to CFLAGS so the flags can be use by implicit rule when creating OBJECTS from SOURCES
- set build executable dependency to OBJECTS
- mark 'clean' rule to be executed even in case the file with the same name exists
- extend 'clean' rule to remove generated OBJECTS
