### ISSUE TITLE
Not found headers

### ISSUE THREAD

**Issue by GGXBoo** [danielpinto8zz6/c-cpp-project-generator#56]
I use this project to create a C project to write GTK programs. The header is `#inclued <gtk/gtk.h>`, but When I try to `make run` got a error not found this header file. This is due to the hermit rule of makefile，so I added
 ```
%.o:%.c
	$(CC) -c $(CFLAGS) $^ -o $@ $(LIBRARIES)
```
Problem solving.
I hope this template can be richer to avoid such mistakes

**Comment by danielpinto8zz6** [comment]
Did you included gtk into libraries?

**Comment by jensen199105** [comment]
i add a header file in "include" path and use #include in main.c. then i build the project but it can't find the header file
![Capture](https://user-images.githubusercontent.com/44580159/81815048-1c25f180-955c-11ea-8b7e-877ecfa49bac.PNG)

**Comment by danielpinto8zz6** [comment]
`#include "add.h"` >> `#include "utility/add.h"`

**Comment by GGXBoo** [comment]
> Did you included gtk into libraries?

No, My GTK library is in the system.
